// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn1QvzUy68Co4Ry8DKlZdmiQ5kPfauf_k',
    appId: '1:614649924328:web:44e2cc6c544a0864de575d',
    messagingSenderId: '614649924328',
    projectId: 'fooddeliveryapp-d5e75',
    authDomain: 'fooddeliveryapp-d5e75.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-d5e75.appspot.com',
    measurementId: 'G-9BQKDTYC0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3y8pPWGKapRxNIesAY7cfcncyV7XiHXE',
    appId: '1:614649924328:android:776c4413a165a281de575d',
    messagingSenderId: '614649924328',
    projectId: 'fooddeliveryapp-d5e75',
    storageBucket: 'fooddeliveryapp-d5e75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJp3-ckwE1LsPzRANxqP3IvdNFjtqY1fA',
    appId: '1:614649924328:ios:fc980e9cd7c16a43de575d',
    messagingSenderId: '614649924328',
    projectId: 'fooddeliveryapp-d5e75',
    storageBucket: 'fooddeliveryapp-d5e75.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJp3-ckwE1LsPzRANxqP3IvdNFjtqY1fA',
    appId: '1:614649924328:ios:fc980e9cd7c16a43de575d',
    messagingSenderId: '614649924328',
    projectId: 'fooddeliveryapp-d5e75',
    storageBucket: 'fooddeliveryapp-d5e75.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn1QvzUy68Co4Ry8DKlZdmiQ5kPfauf_k',
    appId: '1:614649924328:web:e45ecec1ffc896ffde575d',
    messagingSenderId: '614649924328',
    projectId: 'fooddeliveryapp-d5e75',
    authDomain: 'fooddeliveryapp-d5e75.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-d5e75.appspot.com',
    measurementId: 'G-LT94GFYF8V',
  );
}
